### ISSUE TITLE
error when clicking on "Start Tape" before selecting a .tap file

### ISSUE THREAD

**Issue by JDHnz** [EngstromJimmy/ZXSpectrum#12]
If you click on the "Start Tape" button before you've selected a .tap file with the "Chose file" button, then an exception happens and the Blazor error bar appears at the bottom of the page, and the devtools console fills up with lots of "ThreadPool Callback threw an unhandled exception of type System.ArgumentOutOfRangeException" errors

**Comment by EngstromJimmy** [comment]
Thanks =)
I will take a look at that =)
My plan is to introduce a tape player into the UI to replace the button.
And add clearer instructions.

**Comment by JDHnz** [comment]
Yeah, I worked out that I need to select the .tap file, then type J Alt-P Alt-P Enter (for LOAD ""), then click Start Tape. I tried to load a copy of [The Sentinel](https://worldofspectrum.org/archive/software/games/the-sentinel-firebird-software-ltd) that I got from World Of Spectrum, but it looks like it is failing, while that same TAP file works on the ZEsarUX emulator.

**Comment by EngstromJimmy** [comment]
Solved this issue by not showing the start button until you select a tape.
Moving the sentinel issue to a new issue.
