### ISSUE TITLE
problem on https://engstromjimmy.github.io/ZXSpectrum/

### ISSUE THREAD

**Issue by JDHnz** [EngstromJimmy/ZXSpectrum#8]
Check out the included video for the sequence of clicks to get what looks like both the 48k and 128k versions of the emulator running in the same browser window at the same time. Warning: video contains flashing lights!

https://user-images.githubusercontent.com/18640585/172376016-ac2b03d5-0d47-4f27-b69f-2d0937e121ff.mp4

**Comment by EngstromJimmy** [comment]
Ah, yes I can see how that might happen. I'll take a look

**Comment by EngstromJimmy** [comment]
Found the problem, I didn't dispose of the timer
